---
- name: setup npm
  shell: |
    cd /root/react-helloworld/
    echo "" | npm init
    npm config set strict-ssl false
    npm install webpack webpack-dev-server --save
    npm install react react-dom --save
    npm install babel-core babel-loader babel-preset-react babel-preset-es2015 --save
    exit 0
  args:
    executable: /bin/bash
- name: restart all services
  service:
    name: "{{ item }}"
    state: restarted
  with_items:
    - django
    - go
    - react
    - nginx